language: ruby

before_script:
  - mysql -e 'create database richcssparts_test;'

rvm:
  - 2.1.2

cache: bundler

bundler_args: --without doc

notifications:
  email: false
  slack: se2016-fdp-a4:IBtEnlQcbSfkQ43JOgIzbnMP

# whitelist
branches:
  only:
    - master